"""Sprint 4 models caja y auditoria

Revision ID: 172b03dfbaca
Revises: 74382d8bff86
Create Date: 2026-06-17 01:54:19.328343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172b03dfbaca'
down_revision = '74382d8bff86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=100), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('ip_origen', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('cajas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_apertura', sa.DateTime(), nullable=False),
    sa.Column('monto_apertura', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('monto_esperado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monto_real', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('diferencia', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estado', sa.Enum('abierta', 'cerrada', name='estado_caja_enum'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cajas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cajas_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cajas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cajas_usuario_id'))

    op.drop_table('cajas')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_fecha'))
        batch_op.drop_index(batch_op.f('ix_auditoria_accion'))

    op.drop_table('auditoria')
    # ### end Alembic commands ###
