"""Sprint 3 models

Revision ID: 74382d8bff86
Revises: 0002_orders_and_sales
Create Date: 2026-06-17 01:47:48.785358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74382d8bff86'
down_revision = '0002_orders_and_sales'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('unidad_medida', sa.Enum('g', 'kg', 'ml', 'l', 'unidad', name='unidad_medida_enum'), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.CheckConstraint("btrim(nombre) <> ''", name='ck_ingredientes_nombre_not_blank'),
    sa.CheckConstraint('stock_actual >= 0', name='ck_ingredientes_stock_actual_nonnegative'),
    sa.CheckConstraint('stock_minimo >= 0', name='ck_ingredientes_stock_minimo_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_recetas_cantidad_positive'),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], name='fk_recetas_ingrediente_id__ingredientes'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], name='fk_recetas_producto_id__productos'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.create_index('ix_recetas_ingrediente_id', ['ingrediente_id'], unique=False)
        batch_op.create_index('ix_recetas_producto_id', ['producto_id'], unique=False)

    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'salida', 'ajuste', name='tipo_movimiento_enum'), nullable=False),
    sa.Column('motivo', sa.Enum('compra', 'venta', 'merma', 'consumo_interno', 'cancelacion', 'ajuste_manual', name='motivo_movimiento_enum'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_movimientos_cantidad_positive'),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], name='fk_movimientos_ingrediente_id__ingredientes'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], name='fk_movimientos_responsable_id__usuarios'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.create_index('ix_movimientos_fecha', ['fecha'], unique=False)
        batch_op.create_index('ix_movimientos_ingrediente_id', ['ingrediente_id'], unique=False)
        batch_op.create_index('ix_movimientos_responsable_id', ['responsable_id'], unique=False)

    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('metodo', sa.Enum('efectivo', 'transferencia', 'tarjeta', name='metodo_pago_enum'), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(metodo = 'efectivo') OR (btrim(referencia) <> '')", name='ck_pagos_referencia_requerida_tarjeta_transferencia'),
    sa.CheckConstraint('monto > 0', name='ck_pagos_monto_positive'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuarios.id'], name='fk_pagos_responsable_id__usuarios'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], name='fk_pagos_venta_id__ventas'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.create_index('ix_pagos_fecha', ['fecha'], unique=False)
        batch_op.create_index('ix_pagos_responsable_id', ['responsable_id'], unique=False)
        batch_op.create_index('ix_pagos_venta_id', ['venta_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_index('ix_pagos_venta_id')
        batch_op.drop_index('ix_pagos_responsable_id')
        batch_op.drop_index('ix_pagos_fecha')

    op.drop_table('pagos')
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_index('ix_movimientos_responsable_id')
        batch_op.drop_index('ix_movimientos_ingrediente_id')
        batch_op.drop_index('ix_movimientos_fecha')

    op.drop_table('movimientos_inventario')
    with op.batch_alter_table('recetas', schema=None) as batch_op:
        batch_op.drop_index('ix_recetas_producto_id')
        batch_op.drop_index('ix_recetas_ingrediente_id')

    op.drop_table('recetas')
    op.drop_table('ingredientes')
    # ### end Alembic commands ###
